tasks:
  - init: >
      bash -ic "bundle install && gem install rufo"
      gp sync-done bundle
    name: guard
    command: bash -ic "bundle exec guard"

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby
