tasks:
  - init: >
      bash -ic "bundle install"
      gp sync-done bundle
    name: guard
    command: bash -ic "bundle exec guard"
  - name: CLI
    init: gp sync-await bundle
    command: bash -ic "./main.rb"

vscode:
  extensions:
    - rebornix.ruby
    - wingrunr21.vscode-ruby
